version: '3'

services:
  django_app:
    build: .
    volumes:
      - .:/usr/src/app/
    ports:
      - 127.0.0.1:8081:8081
    command:
      bash -c "gunicorn  --workers 3 --bind 8081  crudapp.wsgi:application --error-logfile=error-bqa.log --log-level='error' --capture-output"
    depends_on:
      - databse
  beyondqa-celery:
    build: .
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app/
    command: celery -A crudapp worker --loglevel=INFO --logfile=celery.log
    depends_on:
      - databse

  beyondqa-beat:
      build: .
      volumes:
        - .:/usr/src/app/
      working_dir: /usr/src/app/
      command: celery -A crudapp beat --logfile=beat.log
      depends_on:
        - databse

  databse:
    image: postgres:latest
    volumes:
      - ./dbdata:/var/lib/postgresql/data/
    expose:
      - '5432'
    environment:
      POSTGRES_USER: 'docker'
      POSTGRES_PASSWORD: 'docker'
      POSTGRES_DB: 'docker'


